fix deploy action

diff --git a/.github/workflows/deploy-run-test.yml b/.github/workflows/deploy-run-test.yml
--- a/.github/workflows/deploy-run-test.yml
+++ b/.github/workflows/deploy-run-test.yml
@@ -7,13 +7,12 @@ on:
     types: [ opened, synchronize, reopened ]
 jobs:
   test:
-    name: Deploy and Test
+    name: Docker Deploy and Test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
-
 
       - name: Set up JDK 17
         uses: actions/setup-java@v3
@@ -35,5 +34,5 @@ jobs:
           docker-compose up -d
 
       - name: Run API Test
-        run:  mvn test -P flow_api_test && echo "Run API Test succeeded"|| { echo "Run API Test failed."; exit 1; }
+        run:  mvn test -P flow_api_test -Dapi.url=http://localhost:8080 && echo "Run API Test succeeded"|| { echo "Run API Test failed."; exit 1; }
           
